name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Test Rails ${{matrix.rails}} & Ruby ${{matrix.ruby}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Test all active versions combinations
          # and inactive Rails versions with minimum Ruby version.
          - {rails: "8.1", ruby: "3.4"}
          - {rails: "8.1", ruby: "3.3"}
          - {rails: "8.1", ruby: "3.2"}

          - {rails: "8.0", ruby: "3.4"}
          - {rails: "8.0", ruby: "3.3"}
          - {rails: "8.0", ruby: "3.2"}

          - {rails: "7.2", ruby: "3.4"}
          - {rails: "7.2", ruby: "3.3"}
          - {rails: "7.2", ruby: "3.2"}
          - {rails: "7.2", ruby: "3.1"}

          - {rails: "7.1", ruby: "2.7"}
          - {rails: "7.0", ruby: "2.7"}
          - {rails: "6.1", ruby: "2.5"}
          - {rails: "6.0", ruby: "2.5"}
    steps:
      - uses: actions/checkout@v4

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0

      - name: Setup Ruby ${{matrix.ruby}}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true

      - name: rake test
        run: bundle install && bundle exec rake
        env:
          BUNDLE_GEMFILE: gemfiles/rails-${{matrix.rails}}.gemfile
